language: generic
matrix:
  include:
    - os: linux
      dist: xenial
    - os: linux
      dist: focal
    - os: freebsd
    - os: osx
      osx_image: xcode10.2 # OS X 10.14
    - os: osx
      osx_image: xcode12.5 # OS X 11.3
script:
  - ./test/run.sh
