language: generic
matrix:
  include:
    - os: linux
      dist: trusty
    - os: osx
      osx_image: xcode10.2 # OS X 10.14
    - os: osx
      osx_image: xcode10.1 # OS X 10.13
    - os: osx
      osx_image: xcode9.2  # OS X 10.12
script:
  - ./test/run.sh
