#!/usr/bin/env bash

[ -n "${PKENV_DEBUG}" ] && set -x
source ${PKENV_ROOT}/libexec/helpers

[ ${#} -gt 1 ] && error_and_die "usage: pkenv uninstall [<version>]"

declare version_requested version regex

get_version_requested ${1}

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex=""
else
  version="${version_requested}"
  regex="^${version_requested}$"
fi

[ -n "${version}" ] || error_and_die "Version is not specified"
version="$(pkenv-list | sed -E 's/^(\*| )? //g; s/ \(set by .+\)$//' | grep -e "${regex}" | tail -n 1)"
[ -n "${version}" ] || error_and_die "No versions matching '${1}' found in local"

dst_path="${PKENV_ROOT}/versions/${version}"
if [ -f "${dst_path}/packer" ]; then
  info "Uninstall Packer v${version}"
  rm -r "${dst_path}"
  info "\033[0;32mPacker v${version} is successfully uninstalled\033[0;39m"
fi

