#!/usr/bin/env bash

function error_and_die() {
  echo -e "pkenv: ${0}: ${1}" >&2
  exit 1
}

[ -n "${PKENV_DEBUG}" ] && set -x

[ ${#} -ne 1 ] && error_and_die "usage: pkenv use <version>"

declare version_requested version regex

version_requested="${1}"

if [[ "${version_requested}" =~ ^latest\:.*$ ]]; then
  version="${version_requested%%\:*}"
  regex="${version_requested##*\:}"
elif [[ "${version_requested}" =~ ^latest$ ]]; then
  version="${version_requested}"
  regex=""
else
  version="${version_requested}"
  regex="${version_requested}"
fi

[ -d "${PKENV_ROOT}/versions" ] \
  || error_and_die "No versions of packer installed. Please install one with: pkenv install"

version="$(\ls "${PKENV_ROOT}/versions" \
  | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
  | grep -e "${regex}" \
  | head -n 1
)"

[ -n "${version}" ] || error_and_die "No installed versions of packer matched '${1}'"

target_path=${PKENV_ROOT}/versions/${version}
[ -f ${target_path}/packer ] \
  || error_and_die "Version directory for ${version} is present, but the packer binary is not! Manual intervention required."
[ -x ${target_path}/packer ] \
  || error_and_die "Version directory for ${version} is present, but the packer binary is not executable! Manual intervention required. "

echo "${version}" > "${PKENV_ROOT}/version"
packer version || error_and_die "'packer --version' failed. Something is seriously wrong"
