#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Packer version
#
# Usage: pkenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Packer
# version's `bin' directory is at the front.
#
# For example, if the currently selected Packer version is 0.7.0:
#   pkenv exec plan
#
# is equivalent to:
#   PATH="$PKENV_ROOT/versions/0.7.0/bin:$PATH" packer plan

set -e
[ -n "${PKENV_DEBUG}" ] && set -x

export PKENV_VERSION="$(pkenv-version-name)"
PK_BIN_PATH="${PKENV_ROOT}/versions/${PKENV_VERSION}/packer"
export PATH="${PK_BIN_PATH}:${PATH}"
"${PK_BIN_PATH}" "${@}"
