#!/usr/bin/env bash

function error_and_die() {
  echo -e "${1}" >&2
  exit 1
}

[ -n "$PKENV_DEBUG" ] && set -x

[ $# -ne 0 ] \
  && error_and_die "usage: pkenv list"

[ -d "${PKENV_ROOT}/versions" ] \
  || error_and_die "No versions available. Please install one with: pkenv install"

set -e
ls -1 "${PKENV_ROOT}/versions" | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3
