#!/usr/bin/env bash
#
# Summary: Run an executable with the selected packer version
#
# Usage: pkenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected packer
# version's `bin' directory is at the front.
#
# For example, if the currently selected packer version is 0.12.2:
#   pkenv exec build
#
# is equivalent to:
#   PATH="$PKENV_ROOT/versions/0.12.2/bin:$PATH" packer build

set -e
[ -n "$PKENV_DEBUG" ] && set -x

PKENV_VERSION="$(pkenv-version-name)"
export PKENV_VERSION
PK_BIN_PATH="${PKENV_ROOT}/versions/${PKENV_VERSION}/packer"
export PATH="${PK_BIN_PATH}:${PATH}"
"$PK_BIN_PATH" "$@"
