#!/usr/bin/env bash

function error_and_die() {
  echo -e "${1}" >&2
  exit 1
}

[ -n "$PKENV_DEBUG" ] && set -x

[ $# -ne 1 ] && error_and_die "usage: pkenv use <version>"

declare version
if [[ "${1}" =~ ^latest\:.*$ ]]; then
  version="${1%%\:*}"
  regex="${1##*\:}"
else
  version="${1}"
fi

[ -d "${PKENV_ROOT}/versions" ] \
  || error_and_die "No versions of packer installed. Please install one with: pkenv install"

[ "${version}" == "latest" ] \
  && version="$(\ls "${PKENV_ROOT}/versions" \
    | sort -t'.' -k 1nr,1 -k 2nr,2 -k 3nr,3 \
    | grep -e "${regex}" \
    | head -n 1
  )"

[ -n "${version}" ] || error_and_die "Version not specified or not found"

target_path=${PKENV_ROOT}/versions/${version}
[ -f ${target_path}/packer ] \
  || error_and_die "Packer version ${version} is not installed"

echo "${version}" > "${PKENV_ROOT}/version"
packer version || error_and_die "'packer version' failed. Something is seriously wrong"
