#!/usr/bin/env bash
set -e
[ -n "${PKENV_DEBUG}" ] && set -x
source ${PKENV_ROOT}/libexec/helpers

if [ ${#} -ne 0 ];then
  echo "usage: pkenv list-remote" 1>&2
  exit 1
fi

PKENV_REMOTE="${PKENV_REMOTE:-https://releases.hashicorp.com}"

curlw -sf "${PKENV_REMOTE}/packer/" | grep -o -E "[0-9]+\.[0-9]+\.[0-9]+(-(alpha|rc|beta)([0-9]+)*)?" | uniq
