#!/usr/bin/env bash
#
# Summary: Run an executable with the selected Packer version
#
# Usage: pkenv exec <command> [arg1 arg2...]
#
# Runs an executable by first preparing PATH so that the selected Packer
# version's `bin' directory is at the front.
#
# For example, if the currently selected packer version is 0.12.2:
#   pkenv exec build
#
# is equivalent to:
#   PATH="$PKENV_ROOT/versions/0.12.2/bin:$PATH" packer build

set -e
[ -n "${PKENV_DEBUG}" ] && set -x

export PKENV_VERSION="$(pkenv-version-name)"
TF_BIN_PATH="${PKENV_ROOT}/versions/${PKENV_VERSION}/packer"
export PATH="${TF_BIN_PATH}:${PATH}"
"${TF_BIN_PATH}" "${@}"
