#!/usr/bin/env bash

function error_and_die() {
  echo -e "${1}" >&2
  exit 1
}

[ -n "${PKENV_DEBUG}" ] && set -x

[ $# -gt 1 ] && error_and_die "usage: pkenv uninstall [<version>]"

declare version regex
if [[ "${1}" =~ ^latest\:.*$ ]]; then
  version="${1%%\:*}"
  regex="${1##*\:}"
else
  version="${1}"
fi

if [ "${version}" == "latest" ]; then
  version="$(pkenv-list | grep -e "${regex}" | head -n 1)"
  [ -n "${version}" ] || error_and_die "No matching version found in local"
elif [ -z "$(pkenv-list | grep "${version}")" ]; then
  error_and_die "Packer version '${version}' doesn't exist in local, please confirm version name."
fi

[ -n "${version}" ] || error_and_die "Version is not specified"

dst_path="${PKENV_ROOT}/versions/${version}"
if [ -f ${dst_path}/packer ]; then 
  echo "Packer v${version} is installed"
  echo "Uninstall Packer v${version}"
  rm -r ${dst_path}
  echo -e "\033[0;32mPacker v${version} is successfully uninstalled\033[0;39m"
fi

